name: Test                           # Workflow 이름
on:                                  # Event 감지
  push:
    branches:
      - master                       
jobs:                                # Job 설정
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v2
      
      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install Dependencies    # 의존 파일 설치
        run: yarn install

      - name: Build                   # React Build
        run: yarn build